version: "3"
services:
  db:
    image: mariadb
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ocean
      LANG: C.UTF-8
      TZ: ${TZ}
    volumes:
      - ./install/db_init:/docker-entrypoint-initdb.d/
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  redis:
    image: redis:latest
    container_name: redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    restart: unless-stopped
    privileged: true
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      TZ: ${TZ}
  web:
    build:
      context: .
      dockerfile: ./install/docker/ocean_web.Dockerfile
    image: ocean_web:v1
    ports:
      - "8080:8080"
    container_name: web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/ocean_ctf:/opt/ocean_ctf
    depends_on:
      - db
      - redis
    restart: always
    working_dir: /opt/ocean_ctf
    command: "uwsgi --ini uwsgi.ini"
    environment:
      TZ: ${TZ}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    container_name: nginx
    volumes:
      - /opt/ocean_ctf/install/nginx.conf:/etc/nginx/nginx.conf
      - /opt/ocean_ctf:/opt/ocean_ctf
    environment:
      TZ: ${TZ}
